apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: victormagardesafio06 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: victormagardesafio06 
    spec:
      containers:
        - name: victormagardesafio06 
          image: desafio06.azurecr.io/victormagardesafio06
          ports:
          - containerPort: 5000