apiVersion: apps/v1
kind: Deployment
metadata:
  name: victormagardesafio06-myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victormagardesafio06
  template:
    metadata:
      labels:
        app: victormagardesafio06
    spec:
      containers:
        - name: healthcheck
          image: victormagardesafio06
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: "mysql+pymysql://jaine:uis71VCal07@179.188.38.79:3306/jaine"
            - name: REDISTOGO_URL
              value: "redis://179.188.38.79:6379"

          ports:
          - containerPort: 5000
