apiVersion : apps/v1
kind: Deployment
metadata:
  name: myapptestdesafio06 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapptestdesafio06 
    spec:
      containers:
        - name: myapptestdesafio06 
          image: desafio06.azurecr.io/myapptestdesafio06
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: "mysql+pymysql://jaine:uis71VCal07@179.188.38.79:3306/jaine"
            - name: REDISTOGO_URL
              value: "redis://179.188.38.79:6379"

          ports:
          - containerPort: 5000
