apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: victormagar06 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: victormagar06 
    spec:
      containers:
        - name: victormagar06 
          image: desafio06.azurecr.io/victormagar06
          ports:
          - containerPort: 5000