apiVersion: v1
kind: Service
metadata:
  labels:
    app: victormagar06  
  name: victormagar06-myapp
  namespace: desafio06
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: victormagar06 
