apiVersion: v1
kind: Service
metadata:
  labels:
    app: victormagar06 
  name: victormagar06-myapp
  namespace: desafio06
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30100
      protocol: TCP
  type: NodePort
  selector:
    app: victormagar06
