apiVersion: v1
kind: Service
metadata:
    name: myapptestdesafio06
    namespace: default    
spec:
    type: LoadBalancer
    ports:
    - port: 5000 
    selector:
        app: myapptestdesafio06
